name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  precompile_nifs:
    name: Precompile NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})

    strategy:
      fail-fast: false
      matrix:
        nif: ["2.17", "2.16", "2.15"]
        job:
          - { target: aarch64-apple-darwin, os: macos-latest }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-apple-darwin, os: macos-15-intel }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }

    runs-on: ${{ matrix.job.os }}

    env:
      RUSTLER_NIF_VERSION: ${{ matrix.nif }}
      CARGO_TARGET_DIR: target

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract project version
        shell: bash
        run: |
          echo "PROJECT_VERSION=$(sed -n 's/^  @version \"\\(.*\\)\"/\\1/p' mix.exs | head -n1)" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: astrodynamics_native
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross }}
          cross-version: v0.2.5
          project-dir: "native/astrodynamics_native"

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

  publish_release:
    name: Publish release assets
    needs: precompile_nifs
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish archives to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.tar.gz
